import random  #导入radmom标准库
print ("从一个列表中随机返回一个元素: ", random.choice(['红色','蓝色','绿色','黄色']))
print ("从一个元组中随机返回一个元素 : ", random.choice(('A级','B级','C级','D级','E级')))
print ("从字符串中随机返回一个字符 : ", random.choice('Python!'))
print()
print ("从一个列表中随机返回两个元素: ", random.sample(['红色','蓝色','绿色','黄色'],2))
print ("从一个元组中随机返回三个元素 : ", random.sample(('A级','B级','C级','D级','E级'),3))
print ("从字符串中随机返回四个字符 : ", random.sample('Python!',4))
print()
print("从1~100之间随机产生一个整数：",random.randint(1,100))
print("从80~100之间随机产生一个整数：",random.randint(80,100))
print()
print("从1~100之间随机产生一个浮点数：",random.uniform(1,100))
print("从80~100之间随机产生一个浮点数：",random.uniform(80,100))
print()
print("从1~100之间随机产生一个整数：",random.randrange(100))
print("从1~99之间随机产生一个奇数：",random.randrange(1,99,2))
print("从3~99之间随机产生一个3的倍数：",random.randrange(3,99,3))
print()
print("在0~1之间产生一个随机数：",random.random())
print()
random.seed()
print("使用默认种子生成随机数：",random.random())
random.seed(10)
print("使用整数种子生成随机数：",random.random())
random.seed("hello",2)
print("使用字符串种子生成随机数：",random.random())
print()
list1 = [12,15,11,99,32,86,52,33]
print("列表中原来的数据：",list1)
random.shuffle(list1)
print("随机排序列表后的数据:",list1)
