import math    #导入math标准库
print ("acos(0.64)的值是 : ", math.acos(0.64))
print ("acos(0)的值是 : ",  math.acos(0))
print ("asin(-1)的值是 : ",  math.asin(-1))
print ("asin(1)的值是 : ",  math.asin(1))
print ("atan(0)的值是 : ",  math.atan(0))
print ("atan(10)的值是 : ",  math.atan(10))
print ("atan2(5，5)的值是 : ",  math.atan2(5,5))
print ("atan2(-10，10)的值是 : ",  math.atan2(-10,10))
print()
print ("cos(3)的值是 : ",  math.cos(3))
print ("cos(-3) 的值是: ",  math.cos(-3))
print ("hypot(3， 2)的值是 : ",  math.hypot(3, 2))
print ("hypot(-3， 3)的值是 : ",  math.hypot(-3, 3))
print ("sin(3)的值是 : ",  math.sin(3))
print ("sin(-3)的值是 : ",  math.sin(-3))
print ("(tan(3)的值是 : ",  math.tan(3))
print ("tan(-3) 的值是: ",  math.tan(-3))
print()
print ("degrees(3)的值是 : ",  math.degrees(3))
print ("degrees(-3)的值是 : ",  math.degrees(-3))
print ("radians(3)的值是 : ",  math.radians(3))
print ("radians(-3)的值是 : ",  math.radians(-3))
