a = set('I like Python!')
b = set('I like Java too!')
print("a集合中的元素：",a,"\n")
print("b集合中的元素：",b,"\n")
print("集合的差、并、交集运算结果：\n")
print("a和b的差集:",a - b)     
print("a和b的并集:",a | b)    
print("a和b的交集:",a & b,"\n")
print("集合的其他运算结果：\n")
print("a和b中不同时存在的元素:",a ^ b)
print("a和b的真子值:",a < b)
print("a和b的子值:",a <= b)
print("a和b的真超值:",a > b)
print("a和b的超值:",a >= b)
print("a和b的相等:",a == b)
print("a和b的不相等:",a != b,"\n")
print("集合的成员测试运算结果：\n")
print("a属于b:",a in b)
print("a不属于b:",a not in b)
