tuple1 = (18, 72, 63,12,16,38,156,369)
tuple2 = ("who", "what", "whose", "when")
print("\ntuple1元组中元素的最大值：",max(tuple1))
print("tuple1元组中元素的最小值：",min(tuple1))
print("\n\ntuple2元组中元素的最大值：",max(tuple2))
print("tuple2元组中元素的最小值：",min(tuple2))
print("\n\ntuple1元组中元素的个数：",len(tuple1))
print("tuple2元组中元素的个数：",len(tuple2))
print("\n\n把元组转换成列表，并显示：",list(tuple1))
print("\n\n把列表为元组，并显示：",tuple(list(tuple1)))
